[package]
name = "sdp-parser-wasm"
version = "0.1.0"
authors = ["Mik <mik@mikbry.com>"]
edition = "2018"
description = "A sdp parser"
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen= "0.2"
